# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-10-22 13:58:24
"""
import arcpy

def splittool():  # split_tool

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"C:\Users\HAVE A NICE DAY\OneDrive\Documents\ArcGIS\Projects\MyProject34\MyProject34.atbx")
    india_administrative_state_boundary_shp = "D:\\AGSRT_course\\AGSRT_ArcPy\\study_material\\india_administrative_state_boundary\\india_administrative_state_boundary.shp"
    grid_1_shp = "C:\\Users\\HAVE A NICE DAY\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject34\\grid_1.shp"
    grid_2_shp = "C:\\Users\\HAVE A NICE DAY\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject34\\grid_2.shp"

    # Process: Script (Script) (MyProject34atbx)
    output = "D:\\AGSRT_course\\AGSRT_ArcPy\\ARCPro_file\\output"
    arcpy.MyProject34atbx.Script(input_shapefile=india_administrative_state_boundary_shp, split_features=[grid_1_shp, grid_2_shp], output_directory=output)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\HAVE A NICE DAY\OneDrive\Documents\ArcGIS\Projects\MyProject34\MyProject34.gdb", workspace=r"C:\Users\HAVE A NICE DAY\OneDrive\Documents\ArcGIS\Projects\MyProject34\MyProject34.gdb"):
        splittool()
